# Generated by Django 4.0 on 2022-12-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_admin_user_alter_volunteer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv'),
        ),
    ]
