# Generated by Django 4.0 on 2022-10-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='cairo', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='Egypt', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='district',
            field=models.CharField(default='Maadi', max_length=200),
            preserve_default=False,
        ),
    ]
