# Generated by Django 4.0 on 2022-10-24 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_location_city_location_country_location_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.contactperson', unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.location', unique=True),
        ),
    ]
