# Generated by Django 4.0 on 2022-12-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MLScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoordinatorRating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rating.coordinatorrating')),
                ('MLScore', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rating.mlscore')),
                ('StudentRating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rating.studentrating')),
            ],
        ),
    ]
